AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  sam-app

  Serverless Application to scrape glucose data from dexcom and save to a DynamoDB


Parameters:
    DEXCOMACCOUNTNAME:
        Type: String
    DEXCOMPASSWORD:
        Type: String

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  PollDexcomFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: cron/
      Handler: app.lambda_handler
      Runtime: python3.7
      Environment:
        Variables:
          DEXCOM_ACCOUNT_NAME: !Sub "${DEXCOMACCOUNTNAME}"
          DEXCOM_PASSWORD: !Sub "${DEXCOMPASSWORD}"
          REGION: !Ref "AWS::Region"
      Events:
        PollDexcomScheduledEvent:
          Type: Schedule
          Properties:
            Schedule: rate(2 minutes)
      Policies:
        # Give just CRUD permissions to one table
        - DynamoDBCrudPolicy:
            TableName: !Ref GlucoseTable
  GlucoseTable:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      TableName: Glucose
      AttributeDefinitions:
        - AttributeName: timestamp
          AttributeType: N
      KeySchema:
        - AttributeName: timestamp
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5

Outputs:
  PollDexcomFunction:
    Description: "PollDexcom Lambda Function ARN"
    Value: !GetAtt PollDexcomFunction.Arn
  PollDexcomFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt PollDexcomFunctionRole.Arn
  GlucoseTable:
    Description: "GlucoseTableARN"
    Value: !GetAtt GlucoseTable.Arn
